stages:
  - check
  - deploy

check_index:
  stage: check
  script:
    - if [ ! -f public/index.html ]; then echo "Arquivo index.html não encontrado!"; exit 1; fi

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r public/* .public
  artifacts:
    paths:
      - .public
  only:
    - main

